### ISSUE TITLE
Update Frequency Implementation with Operations

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/spec#219]
The Frequency implementation should match Frequency actions with DSNP Operations from https://github.com/LibertyDSNP/spec/issues/214

**Comment by wesbiggs** [comment]
# Compliance Template

This template is provided for DSNP implementors to outline how developers can map implementation APIs to DSNP requirements.

## Overview

1. What is the name of the DSNP implementation?
1. What version of the DSNP specification is currently supported? 
1. Describe the general architecture of the implementation.
1. Where can developers learn more about the implementation?

## Control Keys

1. How are control keys expressed in the implementation?
1. How do users create control keys?
1. What is the serialization format for control keys?
1. How do users generate control key ownership proofs?
1. What is the serialization format for control key ownership proofs?

## Operations

1. Provide an overview of how DSNP Operations are invoked in the implementation, including the use of Transaction Identifiers.
1. Describe how each DSNP Operation may be invoked, including input parameters, expected outputs, and error handling.
    1. Create Identifier
    1. Retire Identifier
    1. Define Delegation
    1. Revoke Delegation
    1. Add Control Key (optional)
    1. Remove Control Key (optional)
    1. Publish Announcement
    1. Publish Batch

## Records

1. Provide an overview of how DSNP State Change Records are emitted by the implementation, including the use of Transaction Identifiers.
1. Describe how external systems can subscribe to or otherwise view all state changes.
1. Describe the encoding of each DSNP State Change Record.
    1. Identifier Creation Record
    1. Delegation Definition Record
    1. Delegation Revocation Record
    1. Control Key Addition Record (optional)
    1. Control Key Removal Record (optional)
    1. Announcement Published Record
    1. Batch Published Record
    1. Failure Record
