### ISSUE TITLE
Other user can assign ownership of a DSNP Id and handle to my contract without my permission

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/spec#33]
### Steps to reproduce
1. Register a new DSNP Id with a handle and point it at an identity contract owned by user A.
2. Transfer ownership of that DSNP Id to a contract owned by user B

### Expected behavior

User A AND user B should be required to approve the transfer of the DSNP Id to user B

### Actual behavior

Only user A is required to approve the transfer of the DSNP Id

### Any other comments?

It is possible this is the desired outcome and it is an ok result.

**Comment by acruikshank** [comment]
If this is acceptible, then we should remove authorization from the initial `register` call as well (since it can be defeated with this mechanism). 

### Arguments for requiring authorization before assignment:

Allowing anyone to register an identity to your contract could be used to embarrass the target, either by assigning an embarrassing handle to the contract, or by engaging in embarrassing social media conduct and then transferring the contract over. 

Either way, recognizing the connection requires some sleuthing, and it, of course, would be deniable. This is similar to the reason Github started requiring authorization before adding people to open source projects (although this would likely be a lot less public).

### Arguments against:

Adding this authorization will prevent direct transfer of a handle to two discrete (untrusted) entities. It won't be simple, for example, to sell a handle. It will be possible to transfer to an intermediate account with both identities, that will allow the buyer to transfer it again to their contract. 

In theory a special purpose contract could be created to do this without allowing the seller to take it back. It's also possible for the seller to change to a different handle, which would free up the handle (not the identity), which would allow the buyer to register it. There would be a danger someone could pick it up in the meantime.

**Comment by wilwade** [comment]
In discussion with @acruikshank it was discovered that although this could be blocked, the assignment of a wallet address as delegate to a different identity. That would associate that wallet address with both identities. This is effectively impossible to prevent without also preventing custom delegation contracts.

Thus instead we should remove the need IRegistry.registerByEIP712Sig and remove the requirement that IRegistry.register "MUST be called by someone who is authorized on the contract" and instead require that IRegistry.register must check that the address supportsInterface via EIP 165
